---
abstract: 'ShipIt step to announce the upload on Twitter'
author:
  - 'Marcel GrE<uuml>nauer, C<< <marcel@cpan.org> >>'
build_requires:
  Test::More: 0.70
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ShipIt-Step-Twitter
no_index:
  directory:
    - inc
    - t
requires:
  Net::Twitter: 0
  ShipIt: 0
  YAML: 0
  perl: 5.6.0
resources:
  license: http://dev.perl.org/licenses/
version: 0.05
